### ISSUE TITLE
Parsing partial postcode

### ISSUE THREAD

**Issue by zaparka** [threedaymonk/uk_postcode#7]
Hi, thanks for this gem, it's very useful. 
I noticed that when you have a postcode like 'N10 2LE' this is the result for your parse:
```
@area="N", @district="10", @sector="2", @unit="LE"
```
but from the official source, it's this:
```
postcode: "N10 2LE", sector: "N10 2", district: "N10 ", area: "N"
```
Am I missing something or is the sector and district off?
I'm using version  2.1.2 
Thanks Petr

**Comment by threedaymonk** [comment]
This is a difference of interpretation, I think: it's returning the district and sector *components* of the postcode rather than the full scoped district or sector. Otherwise, there would be no unit at all, as it would be the same as the postcode. If you want the *full* district sector you should concatenate all the preceding parts:

    N10 2LE
    ^--------- pc.area
     ^^------- pc.district
        ^----- pc.sector
    ^^^------- pc.area + pc.district # full scoped district
    ^^^ ^----- pc.area + pc.district + pc.sector # full scoped sector

**Comment by zaparka** [comment]
Ahh ok. Make sense, thanks, Paul :).
